name = underch
description = Hume2s Underch mod
depends = default
optional_depends = moreores, flowers, fire, bucket, stairs, moreblocks, walls, advtrains, technic_worldgen, industrialtest, gs_amethyst, gs_emerald, gs_ruby, gs_sapphire, amethyst, emerald, ruby, sapphire, terumet