name = underch
description = Hume2s Underch mod
depends = default
optional_depends = flowers, fire, bucket, stairs, moreblocks, walls, advtrains, industrialtest,  gs_emerald, gs_ruby, gs_sapphire, amethyst, emerald, ruby, sapphire, terumet, quartz, blox
